### ISSUE TITLE
Hypr doesn't give polybar system tray

### ISSUE THREAD

**Issue by ExperiBass** [vaxerski/Hypr#63]
**Please describe the bug**
Polybar can't get the system tray. It's either grayed out or outright missing.

**Steps to reproduce:**
1. Disable Hypr bar.
2. Start polybar.

**Expected behavior**
Polybar should be able to use the system tray, and i should be able to interact with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/33764485/163113102-23102b23-79db-40f8-b8f3-b985ac52af15.png)

**Anything else?**
[confeeg](https://github.com/ExperiBass/linux-dotfiles/blob/master/.config/polybar/config.ini)

**Log:**
[loooooooooooooog](https://github.com/vaxerski/Hypr/files/8478681/hyprlog.txt)

**Comment by vaxerski** [comment]
comment out the tray module, disable bar, relog into hypr and try again. I'll test your config on my machine later today when I get back home

**Comment by vaxerski** [comment]
Should be fixed in ca432cc589b82b5c9142a4cb0b78eed6e95c3e58, the config option is `bar:force_no_tray`, set it to 1 and it should work.

**Comment by ExperiBass** [comment]
> Should be fixed in ca432cc589b82b5c9142a4cb0b78eed6e95c3e58, the config option is `bar:force_no_tray`, set it to 1 and it should work.

Still not interactable, to confirm that I did it right it's `force_no_tray=1` inside `Bar {}`?

**Comment by vaxerski** [comment]
yes. Make sure to restart Hypr after changing the setting.

**Comment by ExperiBass** [comment]
Its still not interactable.

**Comment by vaxerski** [comment]
I've tried to enable focus on NoInterventions, but didn't help.

Although all the icons are there for me, they indeed are not interactable. Perhaps configuring them would help? I'll look more into it in a bit.

I am not recieving (by I, I meant the WM) any ENTER events, which I guess should happen for input...?
